allowBuilds:
  esbuild: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0
  vite-plus: 1.0.0
minimumReleaseAgeExclude:
  - '@kazupon/vp-config'
  - '@iconify-json/simple-icons'
  - '@ox-jsdoc/**'
  - ox-jsdoc
  - '@ox-content/**'
  - vitepress-api-references
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
overrides:
  vite@*: 'catalog:'
