/**
 * Default code formatting configuration for Vite Plus.
 *
 * This module provides utilities to define oxfmt configurations.
 *
 * @example
 * ```ts
 * import { defineConfig } from 'vite-plus'
 * import { defineFmtConfig } from '@kazupon/vp-config'
 *
 * export default defineConfig({
 *   fmt: defineFmtConfig({
 *     // Custom options of `vp fmt` (oxfmt) ...
 *   })
 * })
 * ```
 *
 * @module format
 */

/**
 * @author kazuya kawaguchi (a.k.a. kazupon)
 * @license MIT
 */

import type { FilePattern, FmtConfigOptions, FmtOverrideOptions, VpFmtConfig } from './types.ts'

/**
 * Default coding agent instruction files generated by `vp config`.
 *
 * `vp config` regenerates these files with hard-wrapped lines.
 */
export const defaultAgentInstructionFiles = [
  '**/AGENTS.md',
  '**/CLAUDE.md',
  '**/GEMINI.md',
  '**/.github/copilot-instructions.md',
  '**/.aiassistant/rules/viteplus.md'
] satisfies FilePattern

/**
 * Default format overrides for oxfmt in Vite Plus.
 *
 * Keep the prose wrapping of {@link defaultAgentInstructionFiles | coding agent instruction files}.
 */
export const defaultFmtOverrides = [
  {
    files: defaultAgentInstructionFiles,
    options: {
      proseWrap: 'preserve'
    }
  }
] satisfies FmtOverrideOptions[]

/**
 * Default code formatting configuration for oxfmt in Vite Plus.
 */
export const defaultFmtConfig = {
  semi: false,
  singleQuote: true,
  trailingComma: 'none',
  endOfLine: 'lf',
  arrowParens: 'avoid',
  proseWrap: 'never',
  overrides: defaultFmtOverrides
} satisfies FmtConfigOptions

function cloneFmtOverride(override: FmtOverrideOptions): FmtOverrideOptions {
  return {
    ...override,
    files: [...override.files],
    ...(override.excludeFiles ? { excludeFiles: [...override.excludeFiles] } : {}),
    ...(override.options ? { options: { ...override.options } } : {})
  }
}

/**
 * Define format configuration for Vite Plus.
 *
 * If an options is not provided, the {@link defaultFmtConfig | default configuration} be used.
 * The `overrides` option is appended after the {@link defaultFmtOverrides | default overrides}.
 *
 * @param options - {@link FmtConfigOptions} options for code formatting
 * @returns A {@link VpFmtConfig} plain configuration object for oxfmt in Vite Plus
 */
export function defineFmtConfig(options: FmtConfigOptions = {}): VpFmtConfig {
  const { overrides = [], ...restOptions } = options
  return {
    ...defaultFmtConfig,
    ...restOptions,
    // oxfmt gives precedence to later overrides, so user overrides come after the defaults
    overrides: [...defaultFmtOverrides.map(cloneFmtOverride), ...overrides]
  }
}

export type {
  FmtConfigOptions,
  FmtFormatOptions,
  FmtOverrideOptions,
  VpFmtConfig
} from './types.ts'
