/**
 * @author kazuya kawaguchi (a.k.a. kazupon)
 * @license MIT
 */

/**
 * Local configuration types for Vite Plus config helpers.
 *
 * @module types
 */

/**
 * Opaque lint config generated by {@link defineLintConfig}.
 *
 * This intentionally does not expose Vite+ or Oxlint types.
 */
export type VpLintConfig = Record<string, unknown>

/**
 * Opaque format config generated by {@link defineFmtConfig}.
 *
 * This intentionally does not expose Vite+ or Oxfmt types.
 */
export type VpFmtConfig = Record<string, unknown>

/**
 * Lint rule severity.
 */
export type RuleSeverity = 'allow' | 'off' | 'warn' | 'error' | 'deny' | number

/**
 * Lint rule configuration.
 */
export type RuleConfig = RuleSeverity | unknown[]

/**
 * Lint rule map.
 */
export type RuleMap = Record<string, RuleConfig | undefined>

/**
 * File glob patterns.
 */
export type FilePattern = string[]

/**
 * JavaScript plugin entry for Oxlint JS plugins.
 */
export interface JSPluginEntry {
  /**
   * Plugin name.
   */
  name: string
  /**
   * Plugin package specifier or resolved path.
   */
  specifier: string
}

/**
 * Lint override options.
 */
export interface LintOverrideOptions {
  /**
   * File glob patterns to apply this override to.
   */
  files?: FilePattern
  /**
   * File glob patterns to ignore for this override.
   */
  ignores?: FilePattern
  /**
   * Enabled built-in lint plugins for this override.
   */
  plugins?: string[]
  /**
   * JavaScript plugins for this override.
   */
  jsPlugins?: null | JSPluginEntry[]
  /**
   * Rule configuration for this override.
   */
  rules?: RuleMap
  /**
   * Plugin settings for this override.
   */
  settings?: Record<string, unknown>
  [key: string]: unknown
}

/**
 * Base lint configuration options.
 */
export interface BaseLintConfigOptions {
  /**
   * File glob patterns to ignore.
   */
  ignorePatterns?: string[]
  /**
   * Enabled built-in lint plugins.
   */
  plugins?: string[]
  /**
   * JavaScript plugins.
   */
  jsPlugins?: null | JSPluginEntry[]
  /**
   * Oxlint runtime options.
   */
  options?: Record<string, unknown>
  /**
   * File-specific lint overrides.
   */
  overrides?: LintOverrideOptions[]
  /**
   * Top-level rule configuration.
   */
  rules?: RuleMap
  /**
   * Plugin settings.
   */
  settings?: Record<string, unknown>
  [key: string]: unknown
}

/**
 * Format configuration options.
 */
export interface FmtConfigOptions {
  /**
   * File glob patterns to ignore.
   */
  ignorePatterns?: string[]
  /**
   * Whether to print semicolons.
   */
  semi?: boolean
  /**
   * Whether to use single quotes.
   */
  singleQuote?: boolean
  /**
   * Trailing comma style.
   */
  trailingComma?: 'all' | 'es5' | 'none'
  /**
   * End-of-line style.
   */
  endOfLine?: 'auto' | 'crlf' | 'lf' | 'cr'
  /**
   * Arrow function parentheses style.
   */
  arrowParens?: 'always' | 'avoid'
  /**
   * Markdown prose wrapping style.
   */
  proseWrap?: 'always' | 'never' | 'preserve'
  [key: string]: unknown
}
